### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by eighton46** [eighton46/bagle_map#47]
### 概要
Issueベースの開発を作成

### 実装予定の機能
**【すべてのユーザー】**
- [ ] 検索機能
  - [ ] 現在地周辺検索
  - [ ] フリーワード検索
  - [ ] 評価絞り込み機能
  - [ ] タグ検索機能
- [ ] ルート表示機能
- [ ] 地図及び一覧表示機能
- [ ] 詳細表示機能

**【登録ユーザー】**
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] アカウント情報変更機能
- [ ] コメント投稿機能
- [ ] コメント編集機能
- [ ] コメント削除機能
- [ ] タグ投稿機能
- [ ] タグ編集機能
- [ ] タグ削除機能
- [ ] お気に入り機能
- [ ] お気に入り削除機能

### 必要なページ
- [ ] トップページ
- [ ] 店舗一覧、地図表示ページ
- [ ] 店舗詳細ページ
- [ ] 利用規約ページ
- [ ] プライバシー・ポリシーページ
- [ ] アカウント作成ページ
- [ ] ログインページ
- [ ] マイページ
- [ ] レビュー作成ページ
- [ ] お気に入りページ

**Comment by kashiwagi-rena** [comment]
お疲れ様です。

- ストーリーポイントは、5は大きいので、技術等調べていただきもう少し小さくして下さい。
- 実装順番が明白にわからなかったので、的外れでしたら、無視していただきたいのですが、テーブルや機能作成の際は、できれば認証機能を先に作成されると良いと思います。

**Comment by eighton46** [comment]
お疲れ様です。
レビューありがとうございます。
頂いたレビューに返答させていただきます。

> - ストーリーポイントは、5は大きいので、技術等調べていただきもう少し小さくして下さい。

質問させてください。
具体的にどういった修正を望んでいるのか教えて下さい。
アプリ開発カリキュラム.11「個人開発におけるプロジェクトマネジメント」の記載「最大でも5以下になるように」に沿って設定しましたが、ストーリーポイント5はつけてはいけないということでしょうか。
5が設定されている箇所を3に変更すればよいのでしょうか。
それとも、特定の5が設定されているIssueに対して、ストーリーポイントを下げて欲しいということなのでしょうか。
ストーリーポイントは主観で設定する部分だと認識しています。
経験や知識がなければ、自然と高く設定されてしまうと思います。
現状の自分の判断で設定しておりますので、もし講師サイドの視点で高すぎるのであれば、その基準やIssueの実装内容に係る情報、技術、知識をご教示いただければ幸いです。


> - 実装順番が明白にわからなかったので、的外れでしたら、無視していただきたいのですが、テーブルや機能作成の際は、できれば認証機能を先に作成されると良いと思います。

実装順番は多少の前後はあるとは思いますが、Issueの番号の順で想定しております。
また、認証機能はユーザー登録機能（ユーザー認証）のことでよろしいでしょうか。
MVPリリースの段階ではユーザー登録機能は実装しない予定ですので、あとの方に記載されています。
すべてのユーザーに対して地図検索できる部分まででMVPリリースしたいと考えております。
過去のプルリクエストやREADMEを見ていただけるとわかりやすいかもしれません。

以上、ご回答のほどよろしくお願いいたします。

**Comment by kashiwagi-rena** [comment]
ご返答いただきありがとうございます。

> 経験や知識がなければ、自然と高く設定されてしまうと思います。
現状の自分の判断で設定しておりますので、もし講師サイドの視点で高すぎるのであれば、その基準やIssueの実装内容に係る情報、技術、知識をご教示いただければ幸いです。

ストーリーポイント５の扱いに関してです。
初めての実装に関して言えば、5はとても大きな数字と認識しております。
5という大きな数字をつける場合初めて行うことが多いと認識しております。なので、初めて行うことのissueを記事等をみて、半分ぐらいにしていただき3を2個にするなどしていただくのがベストかと思います。

どんな実装をしなければいけないかを明白にすること。
もし困った際にどんなことをしたのかを明白にし講師陣に相談する。

分けることによりより早く原因が見えてくる場合がありますので、今回はできる範囲でいいので、実装の細分化をしていただきたいです。

> MVPリリースの段階ではユーザー登録機能は実装しない予定ですので、あとの方に記載されています。

承知いたしました。こちらの確認不足で申し訳ございません。

**Comment by eighton46** [comment]
お疲れ様です。
レビューありがとうございます。
頂いたレビューに返答させていただきます。

>ストーリーポイント５の扱いに関してです。
初めての実装に関して言えば、5はとても大きな数字と認識しております。
5という大きな数字をつける場合初めて行うことが多いと認識しております。なので、初めて行うことのissueを記事等をみて、半分ぐらいにしていただき3を2個にするなどしていただくのがベストかと思います。
どんな実装をしなければいけないかを明白にすること。
もし困った際にどんなことをしたのかを明白にし講師陣に相談する。
分けることによりより早く原因が見えてくる場合がありますので、今回はできる範囲でいいので、実装の細分化をしていただきたいです。

ご意見ありがとうございます。
ストーリーポイントの設定に関しまして、意見の相違があることはわかりました。
これ以上話し合っても仕方がないので、ストーリーポイントは3以下に設定しました。
内容に問題があれば、レビューいただければと思います。

最後にストーリーポイントの設定について意見を書かせていただきます。

前回のコメントでも申し上げましたが、アプリ開発のカリキュラムと主張が矛盾しています。
カリキュラムを見て作成した受講生は、5をつけても良いと判断すると思います。
その矛盾については、スクール側で協議していただければと思います。

また、ストーリーポイントの本質はタスクの複雑さや労力を見積もることなので、どの数値を設定しても良いと思います。
設定時の自身のスキルや知識によって主観で設定しますので、他者から言われて変更するということは同意しかねます。
明確な基準があったり、第三者がストーリーポイントを評価できるのであれば話は別ですが。
高く設定されていれば、そのときに調査をしてから着手しようとか、講師陣に質問する状況も加味して進行しようとなるというだけだと思います。
全てではありませんが、一応調べた上で難しいと判断したものに5を設定しています。

また、細分化することでストーリーポイントを下げるとありますが、以下の開発カリキュラム内の表に基づくのであれば、どんなに細分化しても私の場合はストーリーポイントの5を設定すると思います。
なぜなら、学習カリキュラムで教わっていない機能を実装したり、環境構築やデプロイはやったことがないからです。
私の価値観では、どんなに細分化してタスクの量が減っても、タスクの内容がやったことがないこと、想像できないことであれば5をつけます。
どんなに調査しても、やったこのないものは詰まるリスクがあると判断します。

ストーリーポイント | 概要 | 目安見積もり時間
-- | -- | --
1 | 文言修正や簡単な修正レベルのタスク | 2時間
2 | バグ修正や簡単な機能追加レベルのタスク | 4時間
3 | 実装が想像できる通常の機能レベルのタスク | 6時間
5 | 実装を進める上で少し調査が必要であったり詰まりそうなタスク | 10時間

以上、最後になりますがストーリーポイントのようなそれぞれの価値観で設定する部分については、個人の設定を曲げることは難しいと思います。
もし、Issueの内容に不備があるとか、Issue内のタスク量が多いのでこういう風に細分化して欲しいのであれば、具体的なレビューをしてください。
私もIssueの内容については不備がたくさんあると思っております。
よろしくお願いいたします。

**Comment by tmtkzk0823** [comment]
確認させていただきました。
順番にご回答させていただきます。

また、一番下に今回のレビューもお渡しさせていただいているのでご確認下さい。

---

> 前回のコメントでも申し上げましたが、アプリ開発のカリキュラムと主張が矛盾しています。
カリキュラムを見て作成した受講生は、5をつけても良いと判断すると思います。
その矛盾については、スクール側で協議していただければと思います。

ご意見ありがとうございます。こちらスクール側で改めて協議させていただき、今後のレビューに活かしていきたいと思います。


> また、ストーリーポイントの本質はタスクの複雑さや労力を見積もることなので、どの数値を設定しても良いと思います。
設定時の自身のスキルや知識によって主観で設定しますので、他者から言われて変更するということは同意しかねます。
明確な基準があったり、第三者がストーリーポイントを評価できるのであれば話は別ですが。
また、ストーリーポイントの本質はタスクの複雑さや労力を見積もることなので、どの数値を設定しても良いと思います。
設定時の自身のスキルや知識によって主観で設定しますので、他者から言われて変更するということは同意しかねます。
明確な基準があったり、第三者がストーリーポイントを評価できるのであれば話は別ですが。
高く設定されていれば、そのときに調査をしてから着手しようとか、講師陣に質問する状況も加味して進行しようとなるというだけだと思います。
全てではありませんが、一応調べた上で難しいと判断したものに5を設定しています。
また、細分化することでストーリーポイントを下げるとありますが、以下の開発カリキュラム内の表に基づくのであれば、どんなに細分化しても私の場合はストーリーポイントの5を設定すると思います。
なぜなら、学習カリキュラムで教わっていない機能を実装したり、環境構築やデプロイはやったことがないからです。
私の価値観では、どんなに細分化してタスクの量が減っても、タスクの内容がやったことがないこと、想像できないことであれば5をつけます。
どんなに調査しても、やったこのないものは詰まるリスクがあると判断します。

おっしゃる通り、最初のレビュー提出していただく段階では「自身のスキルや知識によって主観で設定」していただくことになるので、ある程度大きいストーリーポイントになることは仕方ないかと思います。
その主観で設定していただいたものを、**我々講師陣が現役エンジニアとして開発してきた知見、今まで見てきた受講生の開発状況を踏まえて、レビューとして意見をお渡しさせていただいています。**

ストーリポイント**5**である**実装を進める上で少し調査が必要であったり詰まりそうなタスク**に関しては、経験者であれば、調べながらの実装でストーリーポイント5を多くつけるのは許容できるかと思いますが、実際に初めて個人開発をされるであろう受講生には**調査**と**実装**を分けて考えていただき、**実装が想像できる通常の機能レベルのタスク(ストーリーポイント3)**にまで落とし込んでもらうために調査のisuue等の作成などの細分化をおすすめさせていただいています。

**実装を進める上で少し調査が必要であったり詰まりそうなタスク（5）** 
   ↓
**調査のタスク（1）** **実装が想像できる通常の機能レベルのタスク(3~4)**
※6時間で実装できなそうであれば3に限らず4等をつけていただいても構いません。

上記のような基準、評価で今回のissueベースの開発にレビューをさせていただいています。

---

> 以上、最後になりますがストーリーポイントのようなそれぞれの価値観で設定する部分については、個人の設定を曲げることは難しいと思います。
もし、Issueの内容に不備があるとか、Issue内のタスク量が多いのでこういう風に細分化して欲しいのであれば、具体的なレビューをしてください。

今回、ストーリーポイント5以下にしていただきたい理由をしっかり伝えきれていなかったことが、今回のレビューで足りなかったことかと思います。こちらも社内で再度確認させていただき、再発防止に努めさせていただければと思います。この度は申し訳ありませんでした。
また、レビューをお渡しさせていただいて、受講生側でどうしてもここは曲げられないこと等ある際も、しっかりその旨受講生からレビュワーにレビューのなかで伝えていただくようにテキストコミュニケーションをとっていきたいと思います。

以上、ご意見へのご返答とさせていただければ幸いです。

---

今回のレビューですが、issueを1つ1つ確認させていただきました。
細分化に関しては機能ごとにしっかりできているかと思います。
qiita等の情報もあり良さそうです。
**issueベースの開発** LGTMです。
