### ISSUE TITLE
MVPリリースレビュー提出

### ISSUE THREAD

**Issue by eighton46** [eighton46/bagle_map#73]
## 各種情報
サービス名：BAGEL_MAP
サービスURL：https://bagel-map.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] 検索機能
  - [ ] 現在地または目的地付近のスポット検索
  - [ ]  Mapと一覧表示（表示範囲のスポットのみ）
  - [ ] 上記のスポットの詳細表示

## READMEレビュー時から変更した機能
- [ ] 検索機能
  - [ ] 現在地または目的地付近のスポット検索　→　現在地付近のスポットのみに変更
  - [ ]  Mapと一覧表示（表示範囲のスポットのみ）　→　スポットを抽出せず、全スポットの表示
  - [ ] 上記のスポットの詳細表示

## サービスイメージがわかるようなスクリーンショット等
https://i.gyazo.com/832444ef800ab510b4ece1a9053d6d47.jpg
https://i.gyazo.com/661a8c54dd29cefbd46d715fb2601c0a.jpg
https://i.gyazo.com/9b7c1f3f985a0b71595787ba47211dd3.jpg

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください！
